version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - 8000:80
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ./web:/var/www/html
    restart: always
    depends_on:
      - php
      - db
  
  php:
    image: php:7.3-fpm
    container_name: php
    restart: always
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./web:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 8989:3306
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_ROOT_PASSWORD= #password
      - MYSQL_USER= #username 
      - MYSQL_PASSWORD= #password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions